### ISSUE TITLE
Delegate to handle scanned barcode is called more than once!?

### ISSUE THREAD

**Issue by githotto** [hyperoslo/BarcodeScanner#35] opened 2017-05-28 20:01 UTC
When using the following code fragment:
`    func barcodeScanner(_ controller: BarcodeScannerController, didCaptureCode code: String, type: String) {
        print("\(type(of: self)).barcodeScanner(,code=\(code),type=\(type)")
        let delayInSeconds = 0.5
        var segueId = ""
        DispatchQueue.main.asyncAfter(deadline: .now() + delayInSeconds) {
        //My scanned code handling goes here ...
        }
}`

I am getting the following output:
`HomeScreenViewController.barcodeScanner(,code=Endoscope,type=org.iso.QRCode
HomeScreenViewController.barcodeScanner(,code=Endoscope,type=org.iso.QRCode
HomeScreenViewController.barcodeScanner(,code=Endoscope,type=org.iso.QRCode
HomeScreenViewController.barcodeScanner(,code=Endoscope,type=org.iso.QRCode
HomeScreenViewController.barcodeScanner(,code=Endoscope,type=org.iso.QRCode
HomeScreenViewController.barcodeScanner(,code=Endoscope,type=org.iso.QRCode`

where I only expect one call! I configure the scanner according to the delegate's example.

How can I prevent this from happening, since I want to call a performSegue(..) call, depending on
the scanned-code. What I see now is that 6 times a specific performSegue() will be called, giving me 6 times the same ViewController on my NavigationController-stack?

Anybody now a means how to prevent the barcodeScanner-delegate callback from being called more than one time?

**Comment by vadymmarkov** [comment] 2017-05-28 21:02
@githotto Hey, did you change `isOneTimeSearch` property to `false`? Because setting it to `true` should prevent delegate from being called multiple times.

**Comment by githotto** [comment] 2017-05-29 06:43
@vaymmarkov Hey, I tried indeed setting isOneTimeSearch to true, but with no noticeable improvement. However when I set the scannerController.codeDelegate, .errorDelegate and .dismissalDelegate to nil in my controller.reset() func, my problems seem to have gone. Should the isOneTimeSearch have the same effect or was it just me (after a long day of bug-fixing), because today you suggestions also seems to work!?

**Comment by jeryRazakarison** [comment] 2017-06-23 13:56
Just one thing to know: when you call controller.reset(), it tells the scanner that it can capture new barcodes.
So, if you call `controller.reset()` in the `didCaptureCode` delegate (like in the example), you tell the scanner that it can scan again as soon as a barcode is scanned.

**Comment by MincDev** [comment] 2017-12-15 09:10
@jeryRazakarison Thank you. That solved my problem!

**Comment by junweimah** [comment] 2017-12-20 08:08
@MincDev how did you solve this?

I have `controller.isOneTimeSearch = true` in my viewDidLoad(), but it still scans for multiple times after the barcodecontroller has been dismissed.

**Comment by MincDev** [comment] 2017-12-20 09:06
@junweimah Remove the `controller.reset()` from the `didCaptureCode` delegate function. In the delegate function do what you need to do with the captured code and call `controller.dismiss(animated: true, completion: nil)` to dismiss the controller.

**Comment by junweimah** [comment] 2017-12-20 09:07
@MincDev 
I did that, it goes back to the previous screen, however the cpu is on 100% all the time after that, and device becomes really hot. any idea?

**Comment by MincDev** [comment] 2017-12-20 09:48
@junweimah I am not sure as mine immediately stops the scanning process and my CPU never reaches 100%. I had the same issue with the scanner scanning multiple times and removing the `controller.reset()` solved it for me. What I am doing is scanning the code, then in the `didCaptureCode` delegate function I am querying the code against a barcode API that returns details. I completely removed the `controller.reset()` function from the delegate.

**Comment by junweimah** [comment] 2017-12-21 03:28
@MincDev 
This is my current didCaptureCode function

```
func barcodeScanner(_ controller: BarcodeScannerController, didCaptureCode code: String, type: String) {
        print("Barcode Data: \(code)")
        print("Symbology Type: \(type)")
        controller.isOneTimeSearch = true
        
        Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { _ in
//            controller.reset(animated: true)
            controller.dismiss(animated: true, completion: nil)
        }
}
```

After a successful scanning, the screen will go back my previous screen, because of `controller.dismiss`, but my cpu goes up to 100%.

I click my scan button to bring user back to the scanning screen, but the 'Looking for your product' loading screen is still there, which is why I am guessing cpu is at 100% all the time.

How do I close the loading other than .reset?

**Comment by MincDev** [comment] 2017-12-21 04:52
@junweimah remove the ‘controller.reset(animated: true) from the function. It is not needed here. If you call it the you are telling the scanner it is ready again to scan. Now you close it while you told it to get ready for scanning and that is why your cpu is at 100%. Just remove the reset and you will see everything wil work

**Comment by junweimah** [comment] 2017-12-21 04:55
@MincDev 
Actually i commented off that part. I try scanning for the first time, and then try to scan again to test whether it is running in the background, and I found that it won't scan for the second time, which is working.

But for some reason when I come back to the scanning screen, the loading screen(with the spinning square) is still there

**Comment by MincDev** [comment] 2017-12-21 04:56
@junweimah I also do not have the ‘isOneTimeSearch = false’ in my delegate. I have nothing other than dismiss and just calling a function to for the API. Try taking the dismiss out of the scheduled timer. If that still doesnt work, then the problem is somewhere else. Maybe in the way you call the scanner to open?

**Comment by junweimah** [comment] 2017-12-21 05:03
Possibly, ill have a further look, thanks

**Comment by vadymmarkov** [comment] 2018-01-29 22:04
As I commented before, setting `isOneTimeSearch` property to `true` prevents delegate from being called multiple times. Please also note that you should set this property before you present `BarcodeScannerViewController`.

**Closed by vadymmarkov** 2018-01-29 22:04 UTC
