### ISSUE TITLE
Navigation bar not displayed when scanner presented modally

### ISSUE THREAD

**Issue by kjakm** [hyperoslo/BarcodeScanner#39] opened 2017-06-03 14:28 UTC
I have been successfully using the scanner by pushing it on to the navigation stack. Now however I would like to present it. Strangely the built-in navigation bar is hidden. It seems like the `isBeingPresented` check is not returning the correct result.  The navigation bar does show but once the modal animation has completed and the bar has reached the top of the screen it disappears. I have pasted my code below.

```
        // Configure barcode scanner
        let controller = BarcodeScannerController()
        controller.codeDelegate = self
        controller.dismissalDelegate = self
        controller.errorDelegate = self
        controller.hidesBottomBarWhenPushed = true
                
        // Set strings
        BarcodeScanner.Info.loadingText = NSLocalizedString("Retrieving code...", comment: "")
            
        // Display scanner
        navigationController?.present(controller, animated: true, completion: nil)

```

Is there a way I can manually set the navigation bar visibility?

**Comment by festrs** [comment] 2017-06-28 17:42
Same problem here!

**Comment by vadymmarkov** [comment] 2017-07-13 18:33
@kjakm Have you tried to present navigation controller instead? 
```swift
let controller = BarcodeScannerController()
navigationController?.present(UINavigationController(rootViewController: controller), animated: true, completion: nil)
```

**Comment by ptaking** [comment] 2017-07-27 08:19
@vadymmarkov It doesn't work either.

**Comment by jdbarbosa** [comment] 2017-10-17 12:55
can't we remove the `isBeingPresented` check on `setupFrame` ?

**Comment by deanWombourne** [comment] 2017-10-17 13:36
Hi - we are having the same issue in our app, has there been any progress on this? Thanks!

**Comment by deanWombourne** [comment] 2017-10-17 14:55
Oh, this is fixed in the latest version (`3.0.0`), please can we close this issue?

**Comment by vadymmarkov** [comment] 2017-10-17 20:36
I'm glad to hear the problem is solved 👍

**Closed by vadymmarkov** 2017-10-17 20:36 UTC
