### ISSUE TITLE
Change bar text to my custom message

### ISSUE THREAD

**Issue by kwakueshun** [hyperoslo/BarcodeScanner#133] opened 2018-09-26 09:25 UTC
Is there a way that I can change the text that says "Place the barcode within the window to scan.

**Comment by kwakueshun** [comment] 2018-09-26 09:31
So I managed to resolve this. Thanks.

**Comment by andreescajeda** [comment] 2018-10-17 22:58
Duplicate of #107

**Closed** 2018-10-20 19:43 UTC
