### ISSUE TITLE
controller.reset() not working as expected

### ISSUE THREAD

**Issue by rmoffett** [hyperoslo/BarcodeScanner#27] opened 2017-03-14 16:42 UTC
After scanning a barcode the "Looking for your product..." animation will not dismiss. Based on the below code the assumed behavior would be that the scanner would reset so that I can scan another code. Am I missing something?

```
func barcodeScanner(_ controller: BarcodeScannerController, didCaptureCode code: String, type: String) {
    print("Capture Successful")
    print("code: \(code): type: \(type)")
    
    capturedCodes.insert(code)
    
    controller.reset(animated: true)
  }
```

Also, using `controller.resetWithError(message: String?)` does not seem to work correctly either. The error appears briefly but then changes to the "Looking for your product..." animation and remains as describe above.

**Comment by th3m477** [comment] 2017-05-26 10:04
Same issue.

Only way I could get this to work is to wrap the call in a 1 sec timer (bit hacky!). Otherwise reset() gets called, didCaptureCode gets called again, and it loops too quickly to handle the state. Seems to stop after 8-10 calls.

`Timer.scheduledTimer(withTimeInterval: 1.0, repeats: false) { _ in
            controller.reset(animated: true)
        }`

**Comment by Florensvb** [comment] 2017-05-30 09:05
I solved this by re-instantiating the barcodeScanner object after the user is done using it. In this way it is sure to be reset for the next time use. I also had the exact same issues as described above, but I don't believe @th3m477 answer is a very reliable one :) This should definitely be fixed

**Comment by icefall** [comment] 2017-07-11 20:35
Same problem here! Solved using @th3m477 answer.

**Comment by dbismut** [comment] 2017-10-21 15:56
Same problem. Looks like this happens when you reset the controller before the "Looking for your product...".

**Comment by thebluepotato** [comment] 2017-10-25 20:48
I can confirm! This is really bad when you have a product lookup that is quite fast...

**Comment by vadymmarkov** [comment] 2017-10-27 07:40
As @jeryRazakarison said https://github.com/hyperoslo/BarcodeScanner/issues/35#issuecomment-310672164 `reset` tells the scanner that it can capture new barcodes. If you want to hide barcode scanner controller just call `dismiss` like you usually do.

**Comment by martheli** [comment] 2017-11-10 02:59
Any plan to get this fixed and merged into master? Using `dismiss` does not dismiss the scanner controller.

**Comment by vadymmarkov** [comment] 2018-01-29 21:57
Closing due to inactivity. Lets us know if you have any problems in v4.0.0 of the framework.

**Closed by vadymmarkov** 2018-01-29 21:57 UTC
